# Generated by Django 5.2.10 on 2026-04-14 09:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('property', 'Property'), ('financial', 'Financial'), ('form', 'Form'), ('certificate', 'Certificate'), ('guarantee', 'Guarantee'), ('legal', 'Legal')], max_length=20)),
                ('source', models.CharField(choices=[('seller_provides', 'Seller Provides'), ('conveyancer_obtains', 'Conveyancer Obtains'), ('buyer_side_provides', 'Buyer Side Provides')], max_length=20)),
                ('required_tier', models.CharField(choices=[('always', 'Always Required'), ('if_applicable', 'If Applicable'), ('leasehold_only', 'Leasehold Only'), ('situational', 'Situational')], max_length=16)),
                ('status', models.CharField(choices=[('have', 'Have'), ('missing', 'Missing'), ('not_applicable', 'Not Applicable'), ('requested', 'Requested')], default='missing', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='sale_tracker/documents/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('na_reason', models.CharField(blank=True, max_length=300)),
                ('helper_text', models.TextField(blank=True)),
                ('is_seed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('delete', 'Delete')], max_length=10)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sale_tracker.document')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=40)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_method', models.CharField(choices=[('seller_email', 'Seller Email'), ('platform_download', 'Platform Download'), ('manual', 'Manual')], max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sale_tracker.document')),
            ],
            options={
                'verbose_name_plural': 'Document deliveries',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=500)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('share_of_freehold', 'Share of Freehold')], max_length=20)),
                ('agent_name', models.CharField(blank=True, max_length=200)),
                ('agent_contact', models.CharField(blank=True, max_length=200)),
                ('seller_conveyancer_name', models.CharField(blank=True, max_length=200)),
                ('seller_conveyancer_contact', models.CharField(blank=True, max_length=200)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_contact', models.CharField(blank=True, max_length=200)),
                ('buyer_conveyancer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_conveyancer_contact', models.CharField(blank=True, max_length=200)),
                ('buyer_position', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mortgage', 'Mortgage'), ('chain', 'Chain')], max_length=10)),
                ('chain_length', models.PositiveIntegerField(default=0)),
                ('target_exchange_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('instructed_at', models.DateTimeField(blank=True, null=True)),
                ('notification_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], default='daily_digest', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_tracker_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_owner', models.CharField(choices=[('seller', 'Seller'), ('seller_conveyancer', "Seller's Conveyancer"), ('buyer', 'Buyer'), ('buyer_conveyancer', "Buyer's Conveyancer"), ('estate_agent', 'Estate Agent'), ('lender', 'Lender'), ('freeholder_or_managing_agent', 'Freeholder / Managing Agent'), ('surveyor', 'Surveyor'), ('local_authority_or_search_provider', 'Local Authority / Search Provider'), ('other', 'Other')], max_length=40)),
                ('level', models.CharField(choices=[('1', 'Check-in'), ('2', 'Follow-up'), ('escalation', 'Escalation')], max_length=12)),
                ('template_key', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('body_text', models.TextField()),
                ('sent_marker', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_drafts', to='sale_tracker.sale')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_date', models.DateField(auto_now_add=True)),
                ('raised_by', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('current_owner', models.CharField(choices=[('seller', 'Seller'), ('seller_conveyancer', "Seller's Conveyancer"), ('buyer', 'Buyer'), ('buyer_conveyancer', "Buyer's Conveyancer"), ('estate_agent', 'Estate Agent'), ('lender', 'Lender'), ('freeholder_or_managing_agent', 'Freeholder / Managing Agent'), ('surveyor', 'Surveyor'), ('local_authority_or_search_provider', 'Local Authority / Search Provider'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('with_seller', 'With Seller'), ('with_conveyancer', 'With Conveyancer'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='sale_tracker.sale')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-raised_date'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sale_tracker.sale'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done')], default='not_started', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sale_tracker.sale')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('sale', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='StageGateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overridden_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_overrides', to='sale_tracker.sale')),
            ],
            options={
                'ordering': ['-overridden_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('current_owner', models.CharField(choices=[('seller', 'Seller'), ('seller_conveyancer', "Seller's Conveyancer"), ('buyer', 'Buyer'), ('buyer_conveyancer', "Buyer's Conveyancer"), ('estate_agent', 'Estate Agent'), ('lender', 'Lender'), ('freeholder_or_managing_agent', 'Freeholder / Managing Agent'), ('surveyor', 'Surveyor'), ('local_authority_or_search_provider', 'Local Authority / Search Provider'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_on_other', 'Waiting on Other'), ('done', 'Done'), ('n_a', 'Not Applicable')], default='not_started', max_length=16)),
                ('awaiting_since', models.DateField(blank=True, null=True)),
                ('awaiting_reason', models.CharField(blank=True, max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_seed', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sale_tracker.stage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('letter', 'Letter'), ('in_person', 'In Person')], max_length=12)),
                ('counterparty', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='sale_tracker.sale')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_logs', to='sale_tracker.task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TaskOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_owner', models.CharField(choices=[('seller', 'Seller'), ('seller_conveyancer', "Seller's Conveyancer"), ('buyer', 'Buyer'), ('buyer_conveyancer', "Buyer's Conveyancer"), ('estate_agent', 'Estate Agent'), ('lender', 'Lender'), ('freeholder_or_managing_agent', 'Freeholder / Managing Agent'), ('surveyor', 'Surveyor'), ('local_authority_or_search_provider', 'Local Authority / Search Provider'), ('other', 'Other')], max_length=40)),
                ('to_owner', models.CharField(choices=[('seller', 'Seller'), ('seller_conveyancer', "Seller's Conveyancer"), ('buyer', 'Buyer'), ('buyer_conveyancer', "Buyer's Conveyancer"), ('estate_agent', 'Estate Agent'), ('lender', 'Lender'), ('freeholder_or_managing_agent', 'Freeholder / Managing Agent'), ('surveyor', 'Surveyor'), ('local_authority_or_search_provider', 'Local Authority / Search Provider'), ('other', 'Other')], max_length=40)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='sale_tracker.task')),
            ],
            options={
                'verbose_name_plural': 'Task ownership history',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
