# Generated by Django 5.2.12 on 2026-03-09 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate slugs for existing properties."""
    Property = apps.get_model('api', 'Property')
    for prop in Property.objects.all():
        base = slugify(f"{prop.title}-{prop.postcode}")
        slug = base
        n = 1
        while Property.objects.filter(slug=slug).exclude(pk=prop.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        prop.slug = slug
        prop.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_property_image_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="epc_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
            ),
        ),
        # Step 1: Add slug field WITHOUT unique constraint
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, default=''),
        ),
        # Step 2: Populate slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: Add unique constraint — use SeparateDatabaseAndState to
        # avoid AlterField recreating the _like index that AddField already created
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE UNIQUE INDEX IF NOT EXISTS "api_property_slug_unique" ON "api_property" ("slug");',
                    reverse_sql='DROP INDEX IF EXISTS "api_property_slug_unique";',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="property",
                    name="slug",
                    field=models.SlugField(blank=True, max_length=220, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_seller",
            field=models.BooleanField(
                default=False,
                help_text="Indicates the seller has verified their identity.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("active", "Active"),
                    ("under_offer", "Under Offer"),
                    ("sold_stc", "Sold STC"),
                    ("sold", "Sold"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="api.property",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewer_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="api.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="api.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "property")},
            },
        ),
    ]
