# Generated by Django 4.2.29 on 2026-03-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_servicecategory_serviceprovider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=100)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. "Most Popular"', max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('annual_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('stripe_monthly_price_id', models.CharField(blank=True, default='', help_text='Stripe Price ID for monthly billing', max_length=100)),
                ('stripe_annual_price_id', models.CharField(blank=True, default='', help_text='Stripe Price ID for annual billing', max_length=100)),
                ('max_service_categories', models.IntegerField(default=1, help_text='-1 = unlimited')),
                ('max_locations', models.IntegerField(default=1, help_text='-1 = unlimited')),
                ('max_photos', models.IntegerField(default=0, help_text='-1 = unlimited')),
                ('allow_logo', models.BooleanField(default=False)),
                ('feature_basic_listing', models.BooleanField(default=True)),
                ('feature_local_area_visibility', models.BooleanField(default=True)),
                ('feature_contact_details', models.BooleanField(default=True)),
                ('feature_featured_placement', models.BooleanField(default=False)),
                ('feature_click_through_analytics', models.BooleanField(default=False)),
                ('feature_category_exclusivity', models.BooleanField(default=False)),
                ('feature_priority_search', models.BooleanField(default=False)),
                ('feature_lead_notifications', models.BooleanField(default=False)),
                ('feature_performance_reports', models.BooleanField(default=False)),
                ('feature_account_manager', models.BooleanField(default=False)),
                ('feature_photo_gallery', models.BooleanField(default=False)),
                ('feature_early_access', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Customer ID for billing', max_length=100),
        ),
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_price_id', models.CharField(blank=True, default='', help_text='Stripe Price ID for this add-on', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('compatible_tiers', models.ManyToManyField(blank=True, related_name='available_addons', to='api.subscriptiontier')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('pending', 'Pending')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', help_text='Stripe Subscription ID', max_length=100, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.serviceprovider')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.subscriptiontier')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.serviceprovider')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('stripe_subscription_item_id', models.CharField(blank=True, default='', max_length=100)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_addons', to='api.subscriptionaddon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_addons', to='api.serviceprovidersubscription')),
            ],
            options={
                'unique_together': {('subscription', 'addon')},
            },
        ),
    ]
