# Generated by Django 4.2.29 on 2026-03-09 21:38

from django.db import migrations


def assign_free_tier(apps, schema_editor):
    """Auto-assign free tier subscription to all existing service providers."""
    SubscriptionTier = apps.get_model('api', 'SubscriptionTier')
    ServiceProvider = apps.get_model('api', 'ServiceProvider')
    ServiceProviderSubscription = apps.get_model('api', 'ServiceProviderSubscription')

    free_tier = SubscriptionTier.objects.filter(slug='free').first()
    if not free_tier:
        # Seed hasn't run yet — create a minimal free tier
        free_tier = SubscriptionTier.objects.create(
            name='Free', slug='free', monthly_price=0, annual_price=0,
            max_service_categories=1, max_locations=1, max_photos=0,
            allow_logo=False, feature_basic_listing=True,
            feature_local_area_visibility=True, feature_contact_details=True,
            display_order=0, is_active=True,
        )

    for provider in ServiceProvider.objects.all():
        if not ServiceProviderSubscription.objects.filter(
            provider=provider, status='active'
        ).exists():
            ServiceProviderSubscription.objects.create(
                provider=provider,
                tier=free_tier,
                billing_cycle='monthly',
                status='active',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subscriptiontier_serviceprovider_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_free_tier, migrations.RunPython.noop),
    ]
