# Generated by Django 5.2.12 on 2026-03-11 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_assign_free_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("countered", "Countered"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "counter_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Counter-offer amount from seller",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("seller_notes", models.TextField(blank=True)),
                ("is_cash_buyer", models.BooleanField(default=False)),
                ("is_chain_free", models.BooleanField(default=False)),
                ("mortgage_agreed", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("epc", "EPC Certificate"),
                            ("title_deeds", "Title Deeds"),
                            ("searches", "Searches"),
                            ("ta6", "TA6 Property Information"),
                            ("ta10", "TA10 Fittings & Contents"),
                            ("floorplan", "Floorplan"),
                            ("survey", "Survey Report"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="properties/documents/")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, any authenticated user can view. Otherwise only owner and accepted buyers.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["document_type", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam or Scam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("inaccurate", "Inaccurate Information"),
                            ("duplicate", "Duplicate Listing"),
                            ("sold", "Already Sold"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("actioned", "Actioned"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reward_granted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ViewingSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Specific date, or leave blank for recurring",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_bookings", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ViewingSlotBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="properties/video_thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube or Matterport URL for virtual tour"
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="properties/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="alert_frequency",
            field=models.CharField(
                choices=[
                    ("instant", "Instant"),
                    ("daily", "Daily Digest"),
                    ("weekly", "Weekly Digest"),
                ],
                default="instant",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(
                default=False, help_text="User prefers dark mode"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_enquiries",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_price_drops",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_saved_searches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_viewings",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["status", "-created_at"], name="api_propert_status_045463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["city"], name="api_propert_city_27d4f2_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["postcode"], name="api_propert_postcod_3e7780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="api_propert_price_63c2ab_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type"], name="api_propert_propert_80e661_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["bedrooms"], name="api_propert_bedroom_ce3b14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyview",
            index=models.Index(
                fields=["property", "-viewed_at"], name="api_propert_propert_8fb307_idx"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="api.property",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="api.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="api.property",
            ),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="api.property",
            ),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyflag",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="api.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyflag",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referred_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="viewingslot",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewing_slots",
                to="api.property",
            ),
        ),
        migrations.AddField(
            model_name="viewingslotbooking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="api.viewingslot",
            ),
        ),
        migrations.AddField(
            model_name="viewingslotbooking",
            name="viewing_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_booking",
                to="api.viewingrequest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together={("property", "buyer")},
        ),
        migrations.AlterUniqueTogether(
            name="propertyflag",
            unique_together={("property", "reporter")},
        ),
    ]
