# Generated by Django 4.2.29 on 2026-03-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatmessage_chatroom_offer_propertydocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
