# Generated by Django 5.2.10 on 2026-04-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_conveyancing_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forumtopic',
            name='api_forumto_categor_6af803_idx',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
        migrations.DeleteModel(
            name='ForumCategory',
        ),
    ]
