# Generated by Django 5.2.10 on 2026-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_twofactorchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovidersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('pending', 'Pending')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['property', 'status'], name='api_offer_propert_df3578_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['buyer', 'status'], name='api_offer_buyer_i_bec69c_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['property', 'status'], name='api_viewing_propert_e9e764_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['requester', 'status'], name='api_viewing_request_3a7955_idx'),
        ),
    ]
