# Generated by Django 5.2.10 on 2026-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_serviceprovidersubscription_status_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "is_read"], name="api_chatmes_room_id_e1efa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="api_chatmes_room_id_b4d79b_idx"
            ),
        ),
    ]
