"""Generated by scripts/split_views.py. Edit freely."""
import logging
import math
import requests
from collections import defaultdict
from datetime import timedelta
from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db.models import Q, Count, Sum, Avg, F
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from rest_framework import viewsets, permissions, status, generics
from rest_framework.decorators import api_view, permission_classes, action, throttle_classes
from rest_framework.exceptions import PermissionDenied, ValidationError
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from rest_framework.response import Response
from rest_framework.throttling import UserRateThrottle

from djoser.views import TokenCreateView as DjoserTokenCreateView

from ..models import (
    Property, PropertyImage, PropertyFloorplan, PropertyFeature,
    PriceHistory, SavedProperty, PropertyView,
    ViewingRequest, SavedSearch, PushNotificationDevice, Reply,
    ServiceCategory, ServiceProvider, ServiceProviderReview,
    SubscriptionTier, SubscriptionAddOn, ServiceProviderSubscription,
    ServiceProviderPhoto,
    ChatRoom, ChatMessage,
    ViewingSlot, ViewingSlotBooking,
    Offer, PropertyDocument, PropertyFlag,
    BuyerVerification,
    OpenHouseEvent, OpenHouseRSVP,
    ConveyancerQuoteRequest, ConveyancerQuote,
    NeighbourhoodReview, BoardOrder, BuyerProfile,
    TwoFactorChallenge,
)
from ..serializers import (
    PropertySerializer, PropertyListSerializer, PropertyImageSerializer,
    PropertyFloorplanSerializer, PropertyFeatureSerializer,
    SavedPropertySerializer, DashboardStatsSerializer,
    ViewingRequestSerializer, SavedSearchSerializer, UserProfileSerializer,
    ReplySerializer,
    ServiceCategorySerializer, ServiceProviderListSerializer,
    ServiceProviderDetailSerializer, ServiceProviderReviewSerializer,
    SubscriptionTierSerializer, SubscriptionAddOnSerializer,
    ServiceProviderSubscriptionSerializer, ServiceProviderPhotoSerializer,
    ChatRoomSerializer, ChatMessageSerializer,
    ViewingSlotSerializer,
    OfferSerializer, PropertyDocumentSerializer,
    PropertyFlagSerializer,
    BuyerVerificationSerializer,
    OpenHouseEventSerializer, OpenHouseRSVPSerializer,
    ConveyancerQuoteRequestSerializer, ConveyancerQuoteSerializer,
    NeighbourhoodReviewSerializer, BoardOrderSerializer, BuyerProfileSerializer,
)

logger = logging.getLogger(__name__)
User = get_user_model()

from .base import (
    IsOwnerOrReadOnly, IsServiceProviderOwnerOrReadOnly,
    haversine_distance, TwoFactorVerifyThrottle,
    _calculate_stamp_duty,
)

@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def mortgage_calculator(request):
    """Calculate estimated monthly mortgage payment."""
    try:
        price = float(request.query_params.get('price', 0))
        deposit_pct = float(request.query_params.get('deposit_pct', 10))
        interest_rate = float(request.query_params.get('interest_rate', 4.5))
        term_years = int(request.query_params.get('term_years', 25))
    except (ValueError, TypeError):
        return Response({'detail': 'Invalid parameters.'}, status=status.HTTP_400_BAD_REQUEST)

    buyer_type = request.query_params.get('buyer_type', 'standard')  # standard | first_time | additional
    repayment_type = request.query_params.get('repayment_type', 'repayment')  # repayment | interest_only

    if price <= 0 or term_years <= 0:
        return Response({'detail': 'Price and term must be positive.'}, status=status.HTTP_400_BAD_REQUEST)

    deposit = price * (deposit_pct / 100)
    loan = price - deposit
    monthly_rate = (interest_rate / 100) / 12
    num_payments = term_years * 12

    if repayment_type == 'interest_only':
        # Interest-only: pay only interest each month, loan repaid at end
        monthly_payment = loan * monthly_rate if monthly_rate > 0 else 0
        total_cost = (monthly_payment * num_payments) + loan
        total_interest = monthly_payment * num_payments
    else:
        # Standard repayment mortgage
        if monthly_rate > 0:
            monthly_payment = loan * (monthly_rate * (1 + monthly_rate) ** num_payments) / \
                              ((1 + monthly_rate) ** num_payments - 1)
        else:
            monthly_payment = loan / num_payments
        total_cost = monthly_payment * num_payments
        total_interest = total_cost - loan

    # Stamp duty (England/NI rates as of 2025)
    stamp_duty = _calculate_stamp_duty(price, buyer_type)

    return Response({
        'price': price,
        'deposit': round(deposit, 2),
        'loan_amount': round(loan, 2),
        'monthly_payment': round(monthly_payment, 2),
        'total_cost': round(total_cost, 2),
        'total_interest': round(total_interest, 2),
        'stamp_duty': round(stamp_duty, 2),
        'term_years': term_years,
        'interest_rate': interest_rate,
        'buyer_type': buyer_type,
        'repayment_type': repayment_type,
    })


@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def neighbourhood_info(request, property_pk):
    """Get neighbourhood information for a property's location."""
    prop = get_object_or_404(Property, pk=property_pk)
    postcode = prop.postcode.strip().replace(' ', '+')
    data = {'postcode': prop.postcode, 'city': prop.city, 'county': prop.county}

    # Crime data from police.uk API
    cache_key = f'neighbourhood_{prop.postcode}'
    cached = cache.get(cache_key)
    if cached:
        return Response(cached)

    if prop.latitude and prop.longitude:
        try:
            crime_resp = requests.get(
                'https://data.police.uk/api/crimes-street/all-crime',
                params={'lat': prop.latitude, 'lng': prop.longitude, 'date': '2024-01'},
                timeout=10,
            )
            if crime_resp.status_code == 200:
                crimes = crime_resp.json()
                crime_counts = defaultdict(int)
                for c in crimes:
                    crime_counts[c.get('category', 'other')] += 1
                data['crime_summary'] = dict(crime_counts)
                data['total_crimes_nearby'] = len(crimes)
        except Exception as e:
            logger.debug('Crime API error: %s', e)

    # Postcode data
    try:
        pc_resp = requests.get(
            f'https://api.postcodes.io/postcodes/{prop.postcode.replace(" ", "")}',
            timeout=10,
        )
        if pc_resp.status_code == 200:
            pc_data = pc_resp.json().get('result', {})
            data['region'] = pc_data.get('region')
            data['parliamentary_constituency'] = pc_data.get('parliamentary_constituency')
            data['admin_district'] = pc_data.get('admin_district')
            data['nuts'] = pc_data.get('nuts')
    except Exception as e:
        logger.debug('Postcode API error: %s', e)

    cache.set(cache_key, data, 86400)  # Cache for 24h
    return Response(data)


@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def house_price_lookup(request):
    """Proxy Land Registry Price Paid Data API."""
    postcode = request.query_params.get('postcode', '').strip().upper()
    if not postcode:
        return Response({'error': 'Postcode is required'}, status=400)
    try:
        resp = requests.get(
            'https://landregistry.data.gov.uk/data/ppi/transaction-record.json',
            params={
                'propertyAddress.postcode': postcode,
                '_pageSize': '50',
                '_sort': '-transactionDate',
            },
            timeout=30,
        )
        resp.raise_for_status()
        return Response(resp.json())
    except requests.RequestException as e:
        logger.warning('Land Registry API error: %s', e)
        return Response(
            {'error': 'Could not connect to Land Registry. Please try again.'},
            status=502,
        )


@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def price_comparison(request):
    """Compare property prices in an area using Land Registry data and local listings."""
    postcode = request.query_params.get('postcode', '').strip().upper()
    if not postcode:
        return Response({'error': 'Postcode is required'}, status=400)

    # Get the postcode district (e.g. "BS1" from "BS1 4DJ")
    postcode_district = postcode.split()[0] if ' ' in postcode else postcode[:3]

    # 1. Land Registry sold prices
    land_registry_data = []
    try:
        resp = requests.get(
            'https://landregistry.data.gov.uk/data/ppi/transaction-record.json',
            params={
                'propertyAddress.postcode': postcode,
                '_pageSize': '50',
                '_sort': '-transactionDate',
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        items = data.get('result', {}).get('items', [])
        for item in items:
            land_registry_data.append({
                'address': item.get('propertyAddress', {}).get('paon', ''),
                'price': item.get('pricePaid', 0),
                'date': item.get('transactionDate', ''),
                'property_type': item.get('propertyType', {}).get('prefLabel', [''])[0] if isinstance(item.get('propertyType', {}).get('prefLabel'), list) else item.get('propertyType', {}).get('prefLabel', ''),
                'is_new_build': item.get('newBuild', False),
            })
    except requests.RequestException:
        pass

    # 2. Local listings on our platform
    local_listings = Property.objects.filter(
        status='active',
        postcode__istartswith=postcode_district,
    ).values('id', 'title', 'price', 'property_type', 'bedrooms', 'square_feet', 'slug')[:20]

    # 3. Calculate statistics
    sold_prices = [item['price'] for item in land_registry_data if item.get('price')]
    listing_prices = [float(p['price']) for p in local_listings if p.get('price')]
    all_prices = sold_prices + listing_prices

    stats = {}
    if all_prices:
        stats = {
            'average_price': round(sum(all_prices) / len(all_prices)),
            'median_price': round(sorted(all_prices)[len(all_prices) // 2]),
            'min_price': round(min(all_prices)),
            'max_price': round(max(all_prices)),
            'total_comparables': len(all_prices),
        }

    # 4. Price per square foot from our listings
    sqft_data = [
        float(p['price']) / p['square_feet']
        for p in local_listings
        if p.get('square_feet') and p['square_feet'] > 0
    ]
    if sqft_data:
        stats['avg_price_per_sqft'] = round(sum(sqft_data) / len(sqft_data))

    return Response({
        'postcode': postcode,
        'postcode_district': postcode_district,
        'sold_prices': land_registry_data[:20],
        'local_listings': list(local_listings),
        'statistics': stats,
    })


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def generate_listing_description(request):
    """Generate a property listing description based on provided details.

    Supports a ``brief=true`` flag (or ``tone='brief'``) which returns a short
    1–2 sentence summary suitable for the ``brief_description`` field. The
    long-form path is unchanged and uses the same field inputs as before.
    """
    property_type = request.data.get('property_type', '')
    bedrooms = request.data.get('bedrooms', 0)
    bathrooms = request.data.get('bathrooms', 0)
    reception_rooms = request.data.get('reception_rooms', 0)
    square_feet = request.data.get('square_feet')
    features = request.data.get('features', [])
    location = request.data.get('location', '')
    epc_rating = request.data.get('epc_rating', '')
    tone = request.data.get('tone', 'professional')
    additional_notes = request.data.get('additional_notes', '')
    brief = request.data.get('brief', False) or tone == 'brief'

    # Build description from property details
    type_display = dict(Property.PROPERTY_TYPES).get(property_type, property_type) or 'property'

    # ── Brief mode: single or double sentence, ≤ 300 chars ─────────
    if brief:
        try:
            beds_int = int(bedrooms or 0)
        except (TypeError, ValueError):
            beds_int = 0
        beds_part = f"{beds_int} bedroom " if beds_int else ''
        where = f" in {location}" if location else ''
        sentence_1 = f"A {beds_part}{type_display.lower()}{where}.".strip()

        # Optional second sentence highlighting up to 3 features
        second = ''
        highlight = []
        if isinstance(features, list):
            highlight = [str(f) for f in features[:3] if f]
        if not highlight:
            if epc_rating:
                highlight.append(f"EPC {epc_rating}")
            if square_feet:
                highlight.append(f"approx {square_feet} sq ft")
        if highlight:
            if len(highlight) == 1:
                feature_phrase = highlight[0]
            elif len(highlight) == 2:
                feature_phrase = f"{highlight[0]} and {highlight[1]}"
            else:
                feature_phrase = f"{', '.join(highlight[:-1])} and {highlight[-1]}"
            second = f" Featuring {feature_phrase}."
        brief_text = (sentence_1 + second).strip()
        # Enforce 300 char cap (brief_description field limit)
        if len(brief_text) > 300:
            brief_text = brief_text[:297].rstrip() + '...'
        return Response({
            'description': brief_text,
            'brief': True,
            'tone': 'brief',
            'word_count': len(brief_text.split()),
        })

    # Construct structured description
    parts = []

    if tone == 'estate_agent':
        opener = f"A stunning {bedrooms} bedroom {type_display.lower()}"
    elif tone == 'casual':
        opener = f"This lovely {bedrooms} bedroom {type_display.lower()}"
    else:
        opener = f"A well-presented {bedrooms} bedroom {type_display.lower()}"

    if location:
        opener += f" located in the sought-after area of {location}"
    parts.append(opener + ".")

    # Accommodation details
    rooms = []
    if reception_rooms:
        rooms.append(f"{reception_rooms} reception room{'s' if reception_rooms > 1 else ''}")
    if bathrooms:
        rooms.append(f"{bathrooms} bathroom{'s' if bathrooms > 1 else ''}")
    if rooms:
        parts.append(f"The property comprises {', '.join(rooms)}.")

    if square_feet:
        parts.append(f"Offering approximately {square_feet} sq ft of living space.")

    # Features
    if features:
        feature_list = ', '.join(features[:-1])
        if len(features) > 1:
            feature_list += f" and {features[-1]}"
        else:
            feature_list = features[0]
        parts.append(f"Key features include {feature_list}.")

    # EPC
    if epc_rating:
        parts.append(f"The property has an EPC rating of {epc_rating}.")

    # Additional notes
    if additional_notes:
        parts.append(additional_notes)

    # Closing
    if tone == 'estate_agent':
        parts.append("Internal viewing is highly recommended to fully appreciate what this property has to offer.")
    elif tone == 'casual':
        parts.append("Come and see it for yourself — you won't be disappointed!")
    else:
        parts.append("Viewings are welcomed and encouraged.")

    description = " ".join(parts)

    return Response({
        'description': description,
        'tone': tone,
        'word_count': len(description.split()),
    })


@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def postcode_lookup(request, postcode):
    """Look up a UK postcode via postcodes.io.

    Returns lat/lon, admin_district, country for the given postcode. Does NOT
    return a full address list — the free postcodes.io API only resolves the
    postcode's centroid and admin region. Users still type their house number
    and street manually.
    """
    normalized = (postcode or '').replace(' ', '').upper()
    if not normalized:
        return Response({'detail': 'Postcode required.'}, status=400)

    try:
        resp = requests.get(
            f'https://api.postcodes.io/postcodes/{normalized}',
            timeout=5,
        )
    except requests.RequestException:
        return Response({'detail': 'Postcode lookup unavailable.'}, status=503)

    if resp.status_code == 404:
        return Response({'detail': 'Postcode not found.'}, status=404)
    if resp.status_code != 200:
        return Response({'detail': 'Postcode lookup failed.'}, status=502)

    try:
        payload = resp.json().get('result') or {}
    except ValueError:
        return Response({'detail': 'Invalid response from postcode service.'}, status=502)

    return Response({
        'postcode': payload.get('postcode', normalized),
        'latitude': payload.get('latitude'),
        'longitude': payload.get('longitude'),
        'admin_district': payload.get('admin_district'),
        'admin_county': payload.get('admin_county'),
        'region': payload.get('region'),
        'country': payload.get('country'),
    })


@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def stamp_duty_calculator(request):
    """Calculate UK Stamp Duty Land Tax."""
    try:
        price = float(request.query_params.get('price', 0))
    except (ValueError, TypeError):
        return Response({'error': 'Invalid price'}, status=400)

    is_first_time = request.query_params.get('first_time_buyer', 'false').lower() == 'true'
    is_additional = request.query_params.get('additional_property', 'false').lower() == 'true'
    country = request.query_params.get('country', 'england').lower()

    if country in ('england', 'northern_ireland'):
        # Standard SDLT rates (2024/25)
        if is_first_time and price <= 625000:
            bands = [
                (425000, 0.0),
                (625000, 0.05),
            ]
        else:
            bands = [
                (250000, 0.0),
                (925000, 0.05),
                (1500000, 0.10),
                (float('inf'), 0.12),
            ]
        additional_surcharge = 0.03 if is_additional else 0.0
    elif country == 'scotland':
        # Scottish LBTT
        bands = [
            (145000, 0.0),
            (250000, 0.02),
            (325000, 0.05),
            (750000, 0.10),
            (float('inf'), 0.12),
        ]
        additional_surcharge = 0.06 if is_additional else 0.0
    elif country == 'wales':
        # Welsh LTT
        bands = [
            (225000, 0.0),
            (400000, 0.06),
            (750000, 0.075),
            (1500000, 0.10),
            (float('inf'), 0.12),
        ]
        additional_surcharge = 0.04 if is_additional else 0.0
    else:
        return Response({'error': 'Invalid country. Use: england, scotland, wales, northern_ireland'}, status=400)

    # Calculate banded tax
    tax = 0
    remaining = price
    prev_threshold = 0
    band_breakdown = []

    for threshold, rate in bands:
        if remaining <= 0:
            break
        band_amount = min(remaining, threshold - prev_threshold)
        effective_rate = rate + additional_surcharge
        band_tax = band_amount * effective_rate
        band_breakdown.append({
            'from': prev_threshold,
            'to': min(threshold, price),
            'rate': effective_rate,
            'tax': round(band_tax, 2),
        })
        tax += band_tax
        remaining -= band_amount
        prev_threshold = threshold

    # Estimated total costs
    estimated_legal_fees = 1500 if price < 500000 else 2500
    estimated_survey_cost = 400 if price < 300000 else 700

    return Response({
        'price': price,
        'country': country,
        'is_first_time_buyer': is_first_time,
        'is_additional_property': is_additional,
        'stamp_duty': round(tax, 2),
        'effective_rate': round((tax / price) * 100, 2) if price > 0 else 0,
        'band_breakdown': band_breakdown,
        'total_purchase_costs': {
            'property_price': price,
            'stamp_duty': round(tax, 2),
            'estimated_legal_fees': estimated_legal_fees,
            'estimated_survey_cost': estimated_survey_cost,
            'total': round(price + tax + estimated_legal_fees + estimated_survey_cost, 2),
        },
    })


class NeighbourhoodReviewViewSet(viewsets.ModelViewSet):
    """CRUD for neighbourhood reviews."""
    serializer_class = NeighbourhoodReviewSerializer

    def get_permissions(self):
        if self.action in ['list', 'retrieve']:
            return [permissions.AllowAny()]
        return [permissions.IsAuthenticated()]

    def get_queryset(self):
        postcode_area = self.request.query_params.get('postcode_area', '').strip().upper()
        qs = NeighbourhoodReview.objects.all()
        if postcode_area:
            qs = qs.filter(postcode_area__iexact=postcode_area)
        return qs

    def perform_create(self, serializer):
        serializer.save(reviewer=self.request.user)


@api_view(['GET'])
@permission_classes([permissions.AllowAny])
def neighbourhood_summary(request, postcode_area):
    """Aggregate neighbourhood review scores."""
    postcode_area = postcode_area.strip().upper()
    reviews = NeighbourhoodReview.objects.filter(postcode_area__iexact=postcode_area)

    if not reviews.exists():
        return Response({'postcode_area': postcode_area, 'review_count': 0})

    agg = reviews.aggregate(
        avg_overall=Avg('overall_rating'),
        avg_community=Avg('community_rating'),
        avg_noise=Avg('noise_rating'),
        avg_parking=Avg('parking_rating'),
        avg_shops=Avg('shops_rating'),
        avg_safety=Avg('safety_rating'),
        avg_schools=Avg('schools_rating'),
        avg_transport=Avg('transport_rating'),
        count=Count('id'),
    )

    return Response({
        'postcode_area': postcode_area,
        'review_count': agg['count'],
        'ratings': {
            'overall': round(agg['avg_overall'], 1) if agg['avg_overall'] else None,
            'community': round(agg['avg_community'], 1) if agg['avg_community'] else None,
            'noise': round(agg['avg_noise'], 1) if agg['avg_noise'] else None,
            'parking': round(agg['avg_parking'], 1) if agg['avg_parking'] else None,
            'shops': round(agg['avg_shops'], 1) if agg['avg_shops'] else None,
            'safety': round(agg['avg_safety'], 1) if agg['avg_safety'] else None,
            'schools': round(agg['avg_schools'], 1) if agg['avg_schools'] else None,
            'transport': round(agg['avg_transport'], 1) if agg['avg_transport'] else None,
        },
    })
